# Generated by Django 5.1.2 on 2025-01-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
