# Generated by Django 5.1.2 on 2025-01-30 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={"verbose_name_plural": "Reviews"},
        ),
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
