# Generated by Django 5.1.2 on 2025-01-30 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experience", "0002_initial"),
        ("rooms", "0002_initial"),
        ("wishlists", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlists",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="experience.experience",
            ),
        ),
        migrations.AddField(
            model_name="wishlists",
            name="name",
            field=models.CharField(
                default="<django.db.models.fields.related.ForeignKey>", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="wishlists",
            name="rooms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rooms.room",
            ),
        ),
        migrations.AddField(
            model_name="wishlists",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
