# Generated by Django 5.1.2 on 2025-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("experience", "0002_initial"),
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookings",
            options={"verbose_name_plural": "Bookings"},
        ),
        migrations.AddField(
            model_name="bookings",
            name="check_in",
            field=models.TextField(default="2025-01-01"),
        ),
        migrations.AddField(
            model_name="bookings",
            name="check_out",
            field=models.TextField(default="2025-01-01"),
        ),
        migrations.AddField(
            model_name="bookings",
            name="experiece_date",
            field=models.TextField(default="2025-01-01"),
        ),
        migrations.AddField(
            model_name="bookings",
            name="experience",
            field=models.ManyToManyField(to="experience.experience"),
        ),
        migrations.AddField(
            model_name="bookings",
            name="kind",
            field=models.CharField(
                choices=[("room", "Room"), ("experience", "Expereince")],
                default=1,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="room",
            field=models.ManyToManyField(to="rooms.room"),
        ),
    ]
