# Generated by Django 5.1.2 on 2025-01-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_bookings_user"),
        ("experience", "0002_initial"),
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="guest",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="check_in",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="check_out",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookings",
            name="experiece_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="room",
        ),
        migrations.AddField(
            model_name="bookings",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="experience.experience",
            ),
        ),
        migrations.AddField(
            model_name="bookings",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rooms.room",
            ),
        ),
    ]
